services:
 sqlserver:
  image: mcr.microsoft.com/mssql/server:2022-latest
  volumes:
      - ./data:/initdb
  container_name: sqlserver
  ports:
   - "1433:1433"
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=Coti2024!

